source 'https://supermarket.chef.io'

metadata

group :integration do
  cookbook 'yum-epel'
  cookbook 'apt'
  cookbook 'nodejs_test', path: './test/cookbooks/nodejs_test'
end

cookbook 'nodejs', git: 'git://github.com/redguide/nodejs.git'