source 'https://supermarket.chef.io'

metadata

group :integration do
  cookbook 'yum-epel'
  cookbook 'apt'
  cookbook 'nodejs_test', path: './test/cookbooks/nodejs_test'
end

yum_repository 'rpm' do
    description 'RPM repo for NodeJS'
    baseurl 'https://rpm.nodesource.com/pub_6.x/el/6/x86_64/'
    gpgkey ''
    action :create
end

override['nodejs']['packages'] = ['nodejs']